<?php
/**
 * Product videos.
 *
 * @package SpekTheme
 */

if (!defined('ABSPATH')) {
    exit;
}

$product_id = get_the_ID();
$videos = spek_get_product_resource_urls($product_id, [
    'product_installation_video',
    'product_video',
    'product_videos',
]);

if (empty($videos)) {
    return;
}
?>

<section class="section product-media" id="product-videos">
    <div class="container">
        <div class="section-heading section-heading--compact">
            <span class="eyebrow"><?php esc_html_e('Video', 'spek-theme'); ?></span>
            <h2><?php esc_html_e('Βίντεο προϊόντος', 'spek-theme'); ?></h2>
        </div>

        <div class="product-video-grid">
            <?php foreach ($videos as $index => $video_url) : ?>
                <article class="product-video-card">
                    <div class="product-video-card__frame">
                        <?php
                        $embed = wp_oembed_get($video_url, [
                            'width' => 960,
                            'height' => 540,
                        ]);
                        $extension = strtolower((string) pathinfo((string) wp_parse_url($video_url, PHP_URL_PATH), PATHINFO_EXTENSION));
                        ?>

                        <?php if ($embed) : ?>
                            <?php echo $embed; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- trusted oEmbed HTML generated by WordPress. ?>
                        <?php elseif (in_array($extension, ['mp4', 'webm', 'ogg'], true)) : ?>
                            <video controls preload="metadata">
                                <source src="<?php echo esc_url($video_url); ?>">
                            </video>
                        <?php else : ?>
                            <a class="product-video-card__fallback" href="<?php echo esc_url($video_url); ?>" target="_blank" rel="noopener">
                                <?php esc_html_e('Προβολή βίντεο', 'spek-theme'); ?>
                            </a>
                        <?php endif; ?>
                    </div>

                    <?php if (count($videos) > 1) : ?>
                        <h3><?php printf(esc_html__('Βίντεο %d', 'spek-theme'), (int) $index + 1); ?></h3>
                    <?php endif; ?>
                </article>
            <?php endforeach; ?>
        </div>
    </div>
</section>
